Booking clothes/Models/Reservation.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using Booking_clothes.Service;

namespace Booking_clothes.Models
{
    public class Reservation
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }  // Changed to Id

        public string UserId { get; set; }
        [ForeignKey("UserId")]
        public ApplicationUser User { get; set; }

        public DateTime ReservationDate { get; set; } = DateTime.Now;


        [Required(ErrorMessage = "Status is required.")]
        [StringLength(50, ErrorMessage = "Status cannot be longer than 50 characters.")]
        public string Status { get; set; } = "Pending";
        public decimal TotalAmount { get; set; }

        public bool IsDeleted { get; set; }
        public int AddressId { get; set; }
        [ForeignKey("AddressId")]
        public Address Address { get; set; }
        public ICollection<ReservationDetail> ReservationDetails { get; set; }

    }
}

Booking clothes/Models/ReservationDetail.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Runtime.InteropServices;
using Booking_clothes.Service;

namespace Booking_clothes.Models
{
    public class ReservationDetail
    {

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }  // Changed to Id
        public int ReservationId { get; set; }
        [ForeignKey("ReservationId")]
        public Reservation Reservation { get; set; }
        public int ClothId { get; set; }
        [ForeignKey("ClothId")]
        public Products products { get; set; }
 
        [Required(ErrorMessage = "Quantity is required.")]
        public int Quantity { get; set; } = 1;

        [Required(ErrorMessage = "Delivery date is required.")]
        public DateTime StartReservationDate { get; set; }


        [Required(ErrorMessage = "End date is required.")]
        [DateGreaterThan("StartReservationDate", ErrorMessage = "End date must be greater than or equal to start date.")]
        public DateTime EndReservationDate { get; set; }

    }
}

Booking clothes/Controllers/ReservationDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Booking_clothes.Data;
using Booking_clothes.Models;

namespace Booking_clothes.Controllers
{
    public class ReservationDetailsController : Controller
    {
        private readonly MyContext _context;

        public ReservationDetailsController(MyContext context)
        {
            _context = context;
        }

        // GET: ReservationDetails
        public async Task<IActionResult> Index()
        {
            var myContext = _context.ReservationDetails.Include(r => r.Reservation).Include(r => r.products);
            return View(await myContext.ToListAsync());
        }

        // GET: ReservationDetails/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.ReservationDetails == null)
            {
                return NotFound();
            }

            var reservationDetail = await _context.ReservationDetails
                .Include(r => r.Reservation)
                .Include(r => r.products)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (reservationDetail == null)
            {
                return NotFound();
            }

            return View(reservationDetail);
        }

        // GET: ReservationDetails/Create
        public IActionResult Create()
        {
            ViewData["ReservationId"] = new SelectList(_context.Reservations, "Id", "Status");
            ViewData["ClothId"] = new SelectList(_context.Products, "Id", "Name");
            return View();
        }

        // POST: ReservationDetails/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ReservationId,ClothId,Quantity,StartReservationDate,EndReservationDate")] ReservationDetail reservationDetail)
        {
            
                _context.Add(reservationDetail);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            
            ViewData["ReservationId"] = new SelectList(_context.Reservations, "Id", "Status", reservationDetail.ReservationId);
            ViewData["ClothId"] = new SelectList(_context.Products, "Id", "Name", reservationDetail.ClothId);
            return View(reservationDetail);
        }

        // GET: ReservationDetails/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.ReservationDetails == null)
            {
                return NotFound();
            }

            var reservationDetail = await _context.ReservationDetails.FindAsync(id);
            if (reservationDetail == null)
            {
                return NotFound();
            }
            ViewData["ReservationId"] = new SelectList(_context.Reservations, "Id", "Status", reservationDetail.ReservationId);
            ViewData["ClothId"] = new SelectList(_context.Products, "Id", "Name", reservationDetail.ClothId);
            return View(reservationDetail);
        }

        // POST: ReservationDetails/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ReservationId,ClothId,Quantity,StartReservationDate,EndReservationDate")] ReservationDetail reservationDetail)
        {
            if (id != reservationDetail.Id)
            {
                return NotFound();
            }

            
                try
                {
                    _context.Update(reservationDetail);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReservationDetailExists(reservationDetail.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            
            ViewData["ReservationId"] = new SelectList(_context.Reservations, "Id", "Status", reservationDetail.ReservationId);
            ViewData["ClothId"] = new SelectList(_context.Products, "Id", "Name", reservationDetail.ClothId);
            return View(reservationDetail);
        }

        // GET: ReservationDetails/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.ReservationDetails == null)
            {
                return NotFound();
            }

            var reservationDetail = await _context.ReservationDetails
                .Include(r => r.Reservation)
                .Include(r => r.products)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (reservationDetail == null)
            {
                return NotFound();
            }

            return View(reservationDetail);
        }

        // POST: ReservationDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.ReservationDetails == null)
            {
                return Problem("Entity set 'MyContext.ReservationDetails'  is null.");
            }
            var reservationDetail = await _context.ReservationDetails.FindAsync(id);
            if (reservationDetail != null)
            {
                _context.ReservationDetails.Remove(reservationDetail);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ReservationDetailExists(int id)
        {
          return (_context.ReservationDetails?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Booking clothes/Controllers/ReservationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Booking_clothes.Data;
using Booking_clothes.Models;

namespace Booking_clothes.Controllers
{
    public class ReservationsController : Controller
    {
        private readonly MyContext _context;

        public ReservationsController(MyContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var myContext = _context.Reservations.Include(r => r.User).Include(r => r.Address);
            return View(await myContext.ToListAsync());
        }

        public async Task<IActionResult> ReservationDetails(int id)
        {
            var myContext = _context.ReservationDetails.Include(o => o.Reservation).Include(o => o.products).Where(p => p.ReservationId == id);
            var Reservation = _context.Reservations.Where(p => p.Id == id).Include(u=>u.User).FirstOrDefault();
            ViewBag.TotalAmount = Reservation.TotalAmount;
            ViewBag.userName = Reservation.User.FirstName+" "+ Reservation.User.LastName;

            return View(await myContext.ToListAsync());
        }


        // GET: Reservations/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Reservations == null)
            {
                return NotFound();
            }

            var reservation = await _context.Reservations
                .Include(r => r.Address)
                .Include(r => r.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (reservation == null)
            {
                return NotFound();
            }

            return View(reservation);
        }

        // GET: Reservations/Create
        public IActionResult Create()
        {
            ViewData["AddressId"] = new SelectList(_context.Address, "Id", "AddressLine1");
            ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id");
            return View();
        }

        // POST: Reservations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UserId,ReservationDate,Status,TotalAmount,IsDeleted,AddressId")] Reservation reservation)
        {
            
                _context.Add(reservation);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            
            ViewData["AddressId"] = new SelectList(_context.Address, "Id", "AddressLine1", reservation.AddressId);
            ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id", reservation.UserId);
            return View(reservation);
        }

        // GET: Reservations/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Reservations == null)
            {
                return NotFound();
            }

            var reservation = await _context.Reservations.FindAsync(id);
            if (reservation == null)
            {
                return NotFound();
            }
            ViewData["AddressId"] = new SelectList(_context.Address, "Id", "AddressLine1", reservation.AddressId);
            ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id", reservation.UserId);
            return View(reservation);
        }

        // POST: Reservations/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UserId,ReservationDate,Status,TotalAmount,IsDeleted,AddressId")] Reservation reservation)
        {
            if (id != reservation.Id)
            {
                return NotFound();
            }

           
                try
                {
                    _context.Update(reservation);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReservationExists(reservation.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            
            ViewData["AddressId"] = new SelectList(_context.Address, "Id", "AddressLine1", reservation.AddressId);
            ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id", reservation.UserId);
            return View(reservation);
        }

        // GET: Reservations/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Reservations == null)
            {
                return NotFound();
            }

            var reservation = await _context.Reservations
                .Include(r => r.Address)
                .Include(r => r.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (reservation == null)
            {
                return NotFound();
            }

            return View(reservation);
        }

        // POST: Reservations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Reservations == null)
            {
                return Problem("Entity set 'MyContext.Reservations'  is null.");
            }
            var reservation = await _context.Reservations.FindAsync(id);
            if (reservation != null)
            {
                _context.Reservations.Remove(reservation);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ReservationExists(int id)
        {
          return (_context.Reservations?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        public async Task<IActionResult> SearchByReservationrId(int? id)
        {
            var reservation = await _context.Reservations
                                            .Where(e => e.Id == id)
                                            .ToListAsync();

            return View("Index", reservation);
        }

    }
}

Booking clothes/Views/Reservations/Create.cshtml
@model Booking_clothes.Models.Reservation

@{
    ViewData["Title"] = "Create";
    Layout = "AdminLayout";

}

<div class="container-fluid py-4">
    <div class="row">
        <div class="col-12">
            <div class="card mb-4" style="padding-left:25px">
                <div class="card-header pb-0">
                    <h6 style="margin-bottom:20px">
                        Reservations
                    </h6>

                </div>
                <div class="card-body px-0 pt-0 pb-2">
                    <div class="table-responsive p-0">

                        <h1>Create</h1>

                        <h4>Reservation</h4>
                        <hr />
                        <div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <select asp-for="UserId" class ="form-control" asp-items="ViewBag.UserId"></select>
            </div>
            <div class="form-group">
                <label asp-for="ReservationDate" class="control-label"></label>
                <input asp-for="ReservationDate" class="form-control" />
                <span asp-validation-for="ReservationDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalAmount" class="control-label"></label>
                <input asp-for="TotalAmount" class="form-control" />
                <span asp-validation-for="TotalAmount" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsDeleted" /> @Html.DisplayNameFor(model => model.IsDeleted)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="AddressId" class="control-label"></label>
                <select asp-for="AddressId" class ="form-control" asp-items="ViewBag.AddressId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Booking clothes/Views/Reservations/Delete.cshtml
@model Booking_clothes.Models.Reservation

@{
    ViewData["Title"] = "Delete";
    Layout = "AdminLayout";

}

<div class="container-fluid py-4">
    <div class="row">
        <div class="col-12">
            <div class="card mb-4" style="padding-left:25px">
                <div class="card-header pb-0">
                    <h6 style="margin-bottom:20px">
                        Reservation
                    </h6>
                    <h4>Delete</h4>

                    <h3>Are you sure you want to delete this?</h3>
                </div>
                <div class="card-body px-0 pt-0 pb-2">
                    <div class="table-responsive p-0">

                        <div>
                            <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReservationDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReservationDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalAmount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalAmount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address.AddressLine1)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Booking clothes/Views/Reservations/Details.cshtml
@model Booking_clothes.Models.Reservation

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Reservation</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReservationDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReservationDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalAmount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalAmount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address.AddressLine1)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Booking clothes/Views/Reservations/Edit.cshtml
@model Booking_clothes.Models.Reservation

@{
    ViewData["Title"] = "Edit";
    Layout = "AdminLayout";

}
<div class="container-fluid py-4">
    <div class="row">
        <div class="col-12">
            <div class="card mb-4" style="padding-left:25px">
                <div class="card-header pb-0">
                    <h6 style="margin-bottom:20px">
                        Reservation
                    </h6>
                    <h1>Edit</h1>

                </div>
                <div class="card-body px-0 pt-0 pb-2">
                    <div class="table-responsive p-0">

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <select asp-for="UserId" class="form-control" asp-items="ViewBag.UserId"></select>
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReservationDate" class="control-label"></label>
                <input asp-for="ReservationDate" class="form-control" />
                <span asp-validation-for="ReservationDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalAmount" class="control-label"></label>
                <input asp-for="TotalAmount" class="form-control" />
                <span asp-validation-for="TotalAmount" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsDeleted" /> @Html.DisplayNameFor(model => model.IsDeleted)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="AddressId" class="control-label"></label>
                <select asp-for="AddressId" class="form-control" asp-items="ViewBag.AddressId"></select>
                <span asp-validation-for="AddressId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Booking clothes/Views/Reservations/Index.cshtml
@model IEnumerable<Booking_clothes.Models.Reservation>

@{
    ViewData["Title"] = "Index";
    Layout = "AdminLayout";
}

<div class="container-fluid py-4">
    <div class="row">
        <div class="col-12">
            <div class="card mb-4">
                <div class="card-header pb-0">
                    <h6 style="margin-bottom:20px">
                        Reservations
                    </h6>
                    <div style="margin:10px">
                        <form asp-action="SearchByReservationrId" method="post" class="d-flex align-items-center">
                            <input type="text" name="id" style="display:inline;width:700px;" class="form-control" placeholder="Search by user ID" />
                            <button type="submit" class="btn btn-primary ms-2" style="margin-right:3%">Search</button>
                        </form>
                    </div>
                    
                </div>
                <div class="card-body px-0 pt-0 pb-2">
                    <div class="table-responsive p-0">
                        <table class="table align-items-center mb-0 example1">
                            <thead>

                                <tr>
                                    <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                                    @Html.DisplayNameFor(model => model.Id)
                                    </th>
                                    <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                                    @Html.DisplayNameFor(model => model.User)
            </th>
                                    <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                                    @Html.DisplayNameFor(model => model.ReservationDate)
            </th>
      @*                               <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                                    @Html.DisplayNameFor(model => model.Status)
            </th> *@
                                    <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                                    @Html.DisplayNameFor(model => model.TotalAmount)
            </th>

                                    <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                                    @Html.DisplayNameFor(model => model.Address)
            </th>
                                    <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                                    Reservarion Detalis
            </th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>            
            
            <td class="align-middle text-center">@item.Id</td>


                 <td class="align-middle text-center">
                     @Html.DisplayFor(modelItem => item.User.FirstName)
            </td>
                 <td class="align-middle text-center">
                     @Html.DisplayFor(modelItem => item.ReservationDate)
            </td>
@*                  <td class="align-middle text-center">
                     @Html.DisplayFor(modelItem => item.Status)
            </td> *@
                 <td class="align-middle text-center">
                     @Html.DisplayFor(modelItem => item.TotalAmount)
            </td>
@*                  <td class="align-middle text-center">
                     @Html.DisplayFor(modelItem => item.IsDeleted)
            </td> *@
                 <td class="align-middle text-center">
                     @Html.DisplayFor(modelItem => item.Address.AddressLine1)
            </td>
                 <td class="align-middle text-center">
                     <p style="display:inline;width:700px;background-color:#d00e9a;color:white" class="form-control">
                     @Html.ActionLink("Reservation Details", "ReservationDetails", "Reservations", new { id = item.Id }, null)
                     </p>
            </td>
            <td class="align-middle text-center">
                                    <a asp-action="Edit" asp-route-id="@item.Id">
                        <img src="~/Images/002-document-editor.png" alt="Alternate Text" />
                        Edit
                    </a>
                    <br />
                    <br />
                    <a   asp-action="Delete" asp-route-id="@item.Id">
                        <img src="~/Images/delete (3).png" alt="Alternate Text" />
                        Delete
                    </a>
            </td>
        </tr>
}
    </tbody>
</table>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.11.1/js/jquery.dataTables.min.js" defer></script>
<script src="https://cdn.datatables.net/buttons/2.0.0/js/dataTables.buttons.min.js" defer></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/2.0.0/js/buttons.html5.min.js" defer></script>
<script>
    $(document).ready(function () {
        $('.example1').DataTable({
            dom: 'Bfrtip'
            ,
            buttons: [
                'copyHtml5',
                'excelHtml5',
                'csvHtml5',
                'pdfHtml5'
            ]
        });
    });
</script>